### ISSUE TITLE
great code ! only can you share data? to try your code?

### ISSUE THREAD

**Issue by Sandy4321** [aister2020/KDDCUP_2020_AutoGraph_1st_Place#1]
great code ! only can you share data? to try your code?

**Comment by aister2020** [comment]
> great code ! only can you share data? to try your code?

We have uploaded the competition data to the repository.

**Comment by Sandy4321** [comment]
great thanks
by the way 
will it work for windows?

**Comment by aister2020** [comment]
> great thanks
> by the way
> will it work for windows?
It has only been tested on Linux and MacOS. Need to be modified to work for windows.
